// Managing skins/ -- the registry (skins/index.json) and one manifest
// per skin (skins/<id>/skin.json), exactly the files the game's own
// resolver reads (see ../../js/skins.js). Everything this tab does is a
// file write through save.php or a file removal through delete.php;
// there is no skin state anywhere else to drift from.
//
// What it offers, per the rules the engine already lives by:
//   enable/disable   flips manifest.enabled -- a disabled skin stays on
//                    disk but is never offered or chosen.
//   set default      points the registry's `default` at it -- what every
//                    player without a saved choice gets.
//   copy             a real copy: every override file is fetched and
//                    re-saved under the new id, so the copy is a working
//                    base to edit, not a reference that breaks when the
//                    original changes. Copies are never `system`.
//   delete           non-system skins only -- and the server enforces
//                    that, not this tab (see ../delete.php). Files first,
//                    manifest last, registry after, so a failure partway
//                    leaves a skin that still loads.
//   edit             the manifest as JSON, same treatment the Levels tab
//                    gives level files. Art itself is edited by
//                    re-uploading files at the same paths via the
//                    Graphics tab, or regenerated by tools/*.py.
import * as fs from './fsSave.js';
import { el, fetchJSON, rootUrl, statusParagraph } from './util.js';

const REGISTRY_PATH = 'skins/index.json';
const ID_SHAPE = /^[a-z][a-z0-9-]*$/;

export async function initSkinsTab(panel) {
  await render(panel);
}

async function loadAll() {
  const registry = await fetchJSON(REGISTRY_PATH);
  const skins = [];
  for (const id of registry.skins) {
    try {
      skins.push({ id, manifest: await fetchJSON(`skins/${id}/skin.json`) });
    } catch {
      skins.push({ id, manifest: null });
    }
  }
  return { registry, skins };
}

const saveManifest = (id, manifest) => fs.saveFile(`skins/${id}/skin.json`, `${JSON.stringify(manifest, null, 2)}\n`);
const saveRegistry = (registry) => fs.saveFile(REGISTRY_PATH, `${JSON.stringify(registry, null, 2)}\n`);

// Every file a skin consists of, manifest last -- the order deletion
// walks it in, so the manifest can keep answering delete.php's
// system-skin check until nothing else is left.
function skinFiles(id, manifest) {
  const files = (manifest.overrides ?? []).map((p) => `skins/${id}/${p}`);
  if (manifest.font?.file) files.push(`skins/${id}/${manifest.font.file}`);
  files.push(`skins/${id}/skin.json`);
  return files;
}

async function render(panel) {
  panel.innerHTML = '<p>Loading skins…</p>';
  let data;
  try {
    data = await loadAll();
  } catch (err) {
    panel.innerHTML = '';
    panel.append(el('p', { textContent: `Could not load skins/index.json: ${err.message}` }));
    return;
  }
  const { registry, skins } = data;

  panel.innerHTML = '';
  panel.append(el('p', {
    className: 'tab-intro',
    textContent: 'One folder per skin under skins/, mirroring assets/. A skin overrides only the files its '
      + 'manifest lists; everything else falls back to the base art, so a partial skin is mixed, never broken. '
      + 'The game applies changes on its next load.',
  }));

  const status = statusParagraph();

  for (const { id, manifest } of skins) {
    panel.append(skinCard(panel, registry, id, manifest, status));
  }

  // -- add a new (empty) skin ----------------------------------------------
  const idInput = el('input', { type: 'text', placeholder: 'new-skin-id' });
  const nameInput = el('input', { type: 'text', placeholder: 'Display name' });
  const addBtn = el('button', { textContent: 'Add empty skin' });
  addBtn.addEventListener('click', () => guarded(status, async () => {
    const id = idInput.value.trim();
    if (!ID_SHAPE.test(id)) throw new Error('id must be lowercase letters/digits/dashes, starting with a letter');
    if (registry.skins.includes(id)) throw new Error(`"${id}" already exists`);
    await saveManifest(id, {
      id,
      name: nameInput.value.trim() || id,
      description: '',
      system: false,
      enabled: true,
      overrides: [],
    });
    registry.skins.push(id);
    await saveRegistry(registry);
    await render(panel);
  }));
  const card = el('div', { className: 'card' });
  card.append(el('h3', { textContent: 'New skin' }),
    el('p', { className: 'hint-line', textContent: 'Starts with zero overrides (looks exactly like the base game). Add art by saving files under skins/<id>/assets/... and listing them in the manifest.' }),
    idInput, ' ', nameInput, ' ', addBtn);
  panel.append(card, status);
}

function skinCard(panel, registry, id, manifest, status) {
  const card = el('div', { className: 'card' });
  if (!manifest) {
    card.append(el('h3', { textContent: id }),
      el('p', { textContent: 'skin.json missing or unreadable -- the game skips this skin.' }));
    return card;
  }

  const badges = [
    registry.default === id ? 'DEFAULT' : null,
    manifest.system ? 'SYSTEM' : null,
    manifest.enabled === false ? 'DISABLED' : null,
  ].filter(Boolean).join(' · ');
  card.append(el('h3', { textContent: `${manifest.name} (${id})${badges ? ` — ${badges}` : ''}` }));
  card.append(el('p', {
    className: 'hint-line',
    textContent: `${manifest.description || ''} ${manifest.overrides?.length ?? 0} overridden file(s).`,
  }));

  const row = el('div', {});

  const toggle = el('button', { textContent: manifest.enabled === false ? 'Enable' : 'Disable' });
  toggle.addEventListener('click', () => guarded(status, async () => {
    if (registry.default === id && manifest.enabled !== false) {
      throw new Error('This is the default skin -- point the default elsewhere first.');
    }
    manifest.enabled = manifest.enabled === false;
    await saveManifest(id, manifest);
    await render(panel);
  }));
  row.append(toggle);

  if (registry.default !== id && manifest.enabled !== false) {
    const def = el('button', { textContent: 'Set default' });
    def.addEventListener('click', () => guarded(status, async () => {
      registry.default = id;
      await saveRegistry(registry);
      await render(panel);
    }));
    row.append(' ', def);
  }

  const copy = el('button', { textContent: 'Copy…' });
  copy.addEventListener('click', () => guarded(status, async () => {
    const newId = prompt(`Copy "${id}" as (new id):`, `${id}-copy`);
    if (!newId) return;
    if (!ID_SHAPE.test(newId)) throw new Error('id must be lowercase letters/digits/dashes, starting with a letter');
    if (registry.skins.includes(newId)) throw new Error(`"${newId}" already exists`);
    // A real copy, file by file, so editing it can never bleed into the
    // original. Overrides first, manifest last, mirroring deletion.
    const files = skinFiles(id, manifest).slice(0, -1);
    for (const [i, file] of files.entries()) {
      status.textContent = `Copying ${i + 1}/${files.length}: ${file}`;
      const res = await fetch(rootUrl(file));
      if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
      await fs.saveFile(file.replace(`skins/${id}/`, `skins/${newId}/`), await res.blob());
    }
    await saveManifest(newId, {
      ...manifest, id: newId, name: `${manifest.name} copy`, system: false,
    });
    registry.skins.push(newId);
    await saveRegistry(registry);
    await render(panel);
  }));
  row.append(' ', copy);

  if (!manifest.system) {
    const del = el('button', { textContent: 'Delete…' });
    del.addEventListener('click', () => guarded(status, async () => {
      if (!confirm(`Delete skin "${id}" and all of its files? This cannot be undone.`)) return;
      const files = skinFiles(id, manifest);
      for (const [i, file] of files.entries()) {
        status.textContent = `Deleting ${i + 1}/${files.length}: ${file}`;
        try {
          await fs.deleteFile(file);
        } catch (err) {
          // A file already gone must not strand the rest of the deletion.
          if (!/No such file/.test(err.message)) throw err;
        }
      }
      registry.skins = registry.skins.filter((s) => s !== id);
      if (registry.default === id) registry.default = 'pixel';
      await saveRegistry(registry);
      await render(panel);
    }));
    row.append(' ', del);
  }

  // -- manifest editor ------------------------------------------------------
  const editBtn = el('button', { textContent: 'Edit manifest' });
  const editor = el('textarea', { className: 'json-editor hidden', value: JSON.stringify(manifest, null, 2), spellcheck: false });
  const saveBtn = el('button', { textContent: 'Save manifest', className: 'hidden' });
  editBtn.addEventListener('click', () => {
    editor.classList.toggle('hidden');
    saveBtn.classList.toggle('hidden');
  });
  saveBtn.addEventListener('click', () => guarded(status, async () => {
    const parsed = JSON.parse(editor.value);
    if (parsed.id !== id) throw new Error('the manifest id must match the folder -- copy the skin to rename it');
    await saveManifest(id, parsed);
    await render(panel);
  }));
  row.append(' ', editBtn, ' ', saveBtn);

  card.append(row, editor);
  return card;
}

async function guarded(status, action) {
  try {
    await action();
    status.textContent = 'Saved. The game picks it up on its next load.';
  } catch (err) {
    status.textContent = `Failed: ${err.message}`;
  }
}
